CREATE TABLE IF NOT EXISTS ES_AGGREGATE (
  ID              UUID     PRIMARY KEY,
  VERSION         INTEGER  NOT NULL,
  AGGREGATE_TYPE  TEXT     NOT NULL,
  UNIQUE  (AGGREGATE_TYPE, VERSION)
);

CREATE INDEX IF NOT EXISTS IDX_ES_AGGREGATE_AGGREGATE_TYPE ON ES_AGGREGATE (AGGREGATE_TYPE);

CREATE TABLE IF NOT EXISTS ES_EVENT (
  ID                        UUID       PRIMARY KEY,
  OFFSET_TXID               XID8       NOT NULL,
  AGGREGATE_ID              UUID       NOT NULL REFERENCES ES_AGGREGATE (ID),
  VERSION                   BIGINT     NOT NULL,
  EVENT_TYPE                TEXT       NOT NULL,
  DATA_CONTENT_TYPE         TEXT,
  DATA                      JSON       NOT NULL,
  DATA_BASE64               TEXT,
  META_DATA                 JSON,
  UNIQUE (AGGREGATE_ID, VERSION)
);

CREATE INDEX IF NOT EXISTS IDX_ES_EVENT_TRANSACTION_ID_ID ON ES_EVENT (OFFSET_TXID, ID);
CREATE INDEX IF NOT EXISTS IDX_ES_EVENT_AGGREGATE_ID ON ES_EVENT (AGGREGATE_ID);
CREATE INDEX IF NOT EXISTS IDX_ES_EVENT_VERSION ON ES_EVENT (VERSION);

CREATE TABLE IF NOT EXISTS ES_AGGREGATE_SNAPSHOT (
  ID            UUID     PRIMARY KEY,
  AGGREGATE_ID  UUID     NOT NULL REFERENCES ES_AGGREGATE (ID),
  VERSION       INTEGER  NOT NULL,
  JSON_DATA     JSON     NOT NULL,
  UNIQUE (AGGREGATE_ID, VERSION)
);

CREATE INDEX IF NOT EXISTS IDX_ES_AGGREGATE_SNAPSHOT_AGGREGATE_ID ON ES_AGGREGATE_SNAPSHOT (AGGREGATE_ID);
CREATE INDEX IF NOT EXISTS IDX_ES_AGGREGATE_SNAPSHOT_VERSION ON ES_AGGREGATE_SNAPSHOT (VERSION);

CREATE TABLE IF NOT EXISTS ES_EVENT_SUBSCRIPTION (
  ID                    UUID    PRIMARY KEY,
  SUBSCRIPTION_NAME     TEXT    NOT NULL,
  OFFSET_TXID           XID8    NOT NULL,
  EVENT_ID              BIGINT  NOT NULL
  UNIQUE (SUBSCRIPTION_NAME)
);
