services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
      - $PWD/provision/V1.0__eventstore_schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - $PWD/provision/V1.0__account_schema.sql:/docker-entrypoint-initdb.d/2-schema.sql
    ports:
      - "5432:5432"
    networks:
      - local-network
    restart: unless-stopped
#---------------------------------------------------------------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: pgadmin
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin-data:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - local-network
    restart: unless-stopped
#---------------------------------------------------------------------------------------------------------------------
networks:
  local-network:
    name: sample-network.local
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 171.28.0.0/16
#---------------------------------------------------------------------------------------------------------------------
volumes:
    postgres-data:
    pgadmin-data:
